const PRODUCT_CATEGORY = [
  { label: "텐트", value: "tent" },
  { label: "침낭/매트/해먹", value: "sleeping-bag-mat-hammock" },
  { label: "스토브/화로대", value: "stove-fireplace" },
  { label: "랜턴", value: "lantern" },
  { label: "조리도구", value: "cooking-gear" },
  { label: "기타장비", value: "other-equipment" },
];

const REGION = [
  {
    label: "서울",
    value: "Seoul",
  },
  {
    label: "부산",
    value: "Busan",
  },
  {
    label: "대구",
    value: "Daegu",
  },
  {
    label: "인천",
    value: "Incheon",
  },
  {
    label: "광주",
    value: "Gwangju",
  },
  {
    label: "대전",
    value: "Daejeon",
  },
  {
    label: "울산",
    value: "Ulsan",
  },
  {
    label: "세종",
    value: "Sejong",
  },
  {
    label: "경기",
    value: "Gyeonggi-do",
    cities: [
      { label: "수원", value: "Suwon" },
      { label: "성남", value: "Seongnam" },
      { label: "고양", value: "Goyang" },
      { label: "용인", value: "Yongin" },
      { label: "부천", value: "Bucheon" },
      { label: "안산", value: "Ansan" },
      { label: "안양", value: "Anyang" },
      { label: "남양주", value: "Namyangju" },
      { label: "화성", value: "Hwaseong" },
      { label: "평택", value: "Pyeongtaek" },
      { label: "의정부", value: "Uijeongbu" },
      { label: "파주", value: "Paju" },
      { label: "김포", value: "Gimpo" },
      { label: "광명", value: "Gwangmyeong" },
      { label: "군포", value: "Gunpo" },
      { label: "광주", value: "Gwangju" },
      { label: "이천", value: "Icheon" },
      { label: "양주", value: "Yangju" },
      { label: "오산", value: "Osan" },
      { label: "구리", value: "Guri" },
      { label: "안성", value: "Anseong" },
      { label: "포천", value: "Pocheon" },
      { label: "의왕", value: "Uiwang" },
      { label: "하남", value: "Hanam" },
      { label: "여주", value: "Yeoju" },
      { label: "양평", value: "Yangpyeong" },
      { label: "동두천", value: "Dongducheon" },
      { label: "과천", value: "Gwacheon" },
      { label: "가평", value: "Gapyeong" },
      { label: "연천", value: "Yeoncheon" },
    ],
  },
  {
    label: "강원",
    value: "Gangwon-do",
    cities: [
      { label: "춘천", value: "Chuncheon" },
      { label: "원주", value: "Wonju" },
      { label: "강릉", value: "Gangneung" },
      { label: "동해", value: "Donghae" },
      { label: "태백", value: "Taebaek" },
      { label: "속초", value: "Sokcho" },
      { label: "삼척", value: "Samcheok" },
      { label: "홍천", value: "Hongcheon" },
      { label: "횡성", value: "Hoengseong" },
      { label: "영월", value: "Yeongwol" },
      { label: "평창", value: "Pyeongchang" },
      { label: "정선", value: "Jeongseon" },
      { label: "철원", value: "Cheorwon" },
      { label: "화천", value: "Hwacheon" },
      { label: "양구", value: "Yanggu" },
      { label: "인제", value: "Inje" },
      { label: "고성", value: "Goseong" },
      { label: "양양", value: "Yangyang" },
    ],
  },
  {
    label: "충북",
    value: "Chungcheongbuk-do",
    cities: [
      { label: "청주", value: "Cheongju" },
      { label: "충주", value: "Chungju" },
      { label: "제천", value: "Jecheon" },
      { label: "보은", value: "Boeun" },
      { label: "옥천", value: "Okcheon" },
      { label: "영동", value: "Yeongdong" },
      { label: "증평", value: "Jeungpyeong" },
      { label: "진천", value: "Jincheon" },
      { label: "괴산", value: "Goesan" },
      { label: "음성", value: "Eumseong" },
      { label: "단양", value: "Danyang" },
    ],
  },
  {
    label: "충남",
    value: "Chungcheongnam-do",
    cities: [
      { label: "천안", value: "Cheonan" },
      { label: "공주", value: "Gongju" },
      { label: "보령", value: "Boryeong" },
      { label: "아산", value: "Asan" },
      { label: "서산", value: "Seosan" },
      { label: "논산", value: "Nonsan" },
      { label: "계룡", value: "Gyeryong" },
      { label: "당진", value: "Dangjin" },
      { label: "금산", value: "Geumsan" },
      { label: "부여", value: "Buyeo" },
      { label: "서천", value: "Seocheon" },
      { label: "청양", value: "Cheongyang" },
      { label: "홍성", value: "Hongseong" },
      { label: "예산", value: "Yesan" },
      { label: "태안", value: "Taean" },
    ],
  },
  {
    label: "전북",
    value: "Jeollabuk-do",
    cities: [
      { label: "전주", value: "Jeonju" },
      { label: "군산", value: "Gunsan" },
      { label: "익산", value: "Iksan" },
      { label: "정읍", value: "Jeongeup" },
      { label: "남원", value: "Namwon" },
      { label: "김제", value: "Gimje" },
      { label: "완주", value: "Wanju" },
      { label: "진안", value: "Jinan" },
      { label: "무주", value: "Muju" },
      { label: "장수", value: "Jangsu" },
      { label: "임실", value: "Imsil" },
      { label: "순창", value: "Sunchang" },
      { label: "고창", value: "Gochang" },
      { label: "부안", value: "Buan" },
    ],
  },
  {
    label: "전남",
    value: "Jeollanam-do",
    cities: [
      { label: "목포", value: "Mokpo" },
      { label: "여수", value: "Yeosu" },
      { label: "순천", value: "Suncheon" },
      { label: "나주", value: "Naju" },
      { label: "광양", value: "Gwangyang" },
      { label: "담양", value: "Damyang" },
      { label: "곡성", value: "Gokseong" },
      { label: "구례", value: "Gurye" },
      { label: "고흥", value: "Goheung" },
      { label: "보성", value: "Boseong" },
      { label: "화순", value: "Hwasun" },
      { label: "장흥", value: "Jangheung" },
      { label: "강진", value: "Gangjin" },
      { label: "해남", value: "Haenam" },
      { label: "영암", value: "Yeongam" },
      { label: "무안", value: "Muan" },
      { label: "함평", value: "Hampyeong" },
      { label: "영광", value: "Yeonggwang" },
      { label: "장성", value: "Jangseong" },
      { label: "완도", value: "Wando" },
      { label: "진도", value: "Jindo" },
      { label: "신안", value: "Sinan" },
    ],
  },
  {
    label: "경북",
    value: "Gyeongsangbuk-do",
    cities: [
      { label: "포항", value: "Pohang" },
      { label: "경주", value: "Gyeongju" },
      { label: "김천", value: "Gimcheon" },
      { label: "안동", value: "Andong" },
      { label: "구미", value: "Gumi" },
      { label: "영주", value: "Yeongju" },
      { label: "영천", value: "Yeongcheon" },
      { label: "상주", value: "Sangju" },
      { label: "문경", value: "Mungyeong" },
      { label: "경산", value: "Gyeongsan" },
      { label: "군위", value: "Gunwi" },
      { label: "의성", value: "Uiseong" },
      { label: "청송", value: "Cheongsong" },
      { label: "영양", value: "Yeongyang" },
      { label: "영덕", value: "Yeongdeok" },
      { label: "청도", value: "Cheongdo" },
      { label: "고령", value: "Goryeong" },
      { label: "성주", value: "Seongju" },
      { label: "칠곡", value: "Chilgok" },
      { label: "예천", value: "Yecheon" },
      { label: "봉화", value: "Bonghwa" },
      { label: "울진", value: "Uljin" },
      { label: "울릉", value: "Ulleung" },
    ],
  },
  {
    label: "경남",
    value: "Gyeongsangnam-do",
    cities: [
      { label: "창원", value: "Changwon" },
      { label: "진주", value: "Jinju" },
      { label: "통영", value: "Tongyeong" },
      { label: "사천", value: "Sacheon" },
      { label: "김해", value: "Gimhae" },
      { label: "밀양", value: "Miryang" },
      { label: "거제", value: "Geoje" },
      { label: "양산", value: "Yangsan" },
      { label: "의령", value: "Uiryeong" },
      { label: "함안", value: "Haman" },
      { label: "창녕", value: "Changnyeong" },
      { label: "고성", value: "Goseong" },
      { label: "남해", value: "Namhae" },
      { label: "하동", value: "Hadong" },
      { label: "산청", value: "Sancheong" },
      { label: "함양", value: "Hamyang" },
      { label: "거창", value: "Geochang" },
      { label: "합천", value: "Hapcheon" },
    ],
  },
  {
    label: "제주",
    value: "Jeju-do",
    cities: [
      { label: "제주시", value: "Jeju-si" },
      { label: "서귀포시", value: "Seogwipo-si" },
    ],
  },
];

const PRODUCT_CONDITION_OPTIONS = [
  { value: "new", label: "새상품(미개봉)" },
  { value: "noUse", label: "사용감 없음" },
  { value: "littleUse", label: "사용감 적음" },
  { value: "muchUse", label: "사용감 많음" },
];

const SALE_STATUS = [
  { label: "판매중", value: "판매중" },
  { label: "예약중", value: "예약중" },
  { label: "거래완료", value: "거래완료" },
];

export { PRODUCT_CATEGORY, REGION, PRODUCT_CONDITION_OPTIONS, SALE_STATUS };
